apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idm-infosec-moscow
  namespace: lms
spec:
  secretName: tls-idm-infosec-moscow

  commonName: idm.infosec.moscow
  dnsNames:
    - idm.infosec.moscow

  duration: 2160h
  renewBefore: 360h

  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
