apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: idm
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: yandex-lockbox

  target:
    name: idm
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: {{ .Values.idm.secret.key }}
        version: {{ .Values.idm.secret.version }}
