apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctf-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "0"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "false"
    
    nginx.ingress.kubernetes.io/proxy-body-size: "4G"

    # Timeouts
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

    # Buffers
    nginx.ingress.kubernetes.io/proxy-buffer-size: "4096k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "8182k"

    # WebSocket / SSE for /events
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Strict-Transport-Security";
      add_header Strict-Transport-Security "max-age=0; includeSubdomains" always;
      chunked_transfer_encoding off;
      proxy_cache off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;

spec:
  tls:
    - hosts:
        - {{ .Values.ctfd.domain }}
      secretName: {{ .Values.ctfd.tls_secret_name }}
  rules:
    - host: {{ .Values.ctfd.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctfd
                port:
                  number: 80
  ingressClassName: nginx
