{{- if .Values.backend.deploy }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-backend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - lms.infosec.moscow
      secretName: tls-lms-infosec-moscow
  rules:
    - host: lms.infosec.moscow
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lms-backend
                port:
                  number: 80
---
{{- end }}