{{- if .Values.backend.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  name: lms-backend
  namespace: {{ .Release.namespace }}
spec:
  selector:
    app: lms-backend
  ports:
    - port: 80
      targetPort: {{ .Values.backend.port }}
---
{{- end }}