{{- if .Values.backend.deploy }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lms-postgres
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: yandex-lockbox

  target:
    name: lms-postgres
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: e6q6h3vc89vm830btdp3
        version: e6ql87ik5r10fulr4lsj
---
{{- end }}