{{- if .Values.landing.deploy }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx

    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "0"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Strict-Transport-Security";
      add_header Strict-Transport-Security "max-age=0; includeSubdomains" always;

spec:
  tls:
    - hosts:
        - infosec.moscow
      secretName: tls-infosec-moscow
  rules:
    - host: infosec.moscow
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lms-landing
                port:
                  number: 80
---
{{- end }}