lms_domain: mosh.infosec.moscow
lms_tls_cert: tls-mosh-infosec-moscow
lms_s3_bucket: mosh-infosec-moscow

backend:
  image:
    repository: cr.yandex/crpi7be6fcnum9d5jo38/lms-mosh-backend
    tag: 0.0.1

landing:
  deploy: false