lms_domain: mosh.infosec.moscow
lms_tls_cert: tls-mosh-infosec-moscow
lms_s3_bucket: mosh-infosec-moscow
ctfd_domain: mosh-ctfd.infosec.moscow

backend:
  image:
    repository: cr.yandex/crpi7be6fcnum9d5jo38/lms-mosh-backend
    tag: 0.0.1
  secret:
    key: e6qifkcl5445su046f67
    version: e6qac28oioq4ei8l7s3i

landing:
  deploy: false