lms_domain: lms.infosec.moscow
lms_tls_cert: tls-lms-infosec-moscow
lms_s3_bucket: lms-infosec-moscow
ctfd_domain: ctfd.infosec.moscow
idm_domain: idm.infosec.moscow
idm_tls_cert: tls-idm-infosec-moscow

backend:
  deploy: true
  port: 8080
  replicas: 2
  secret:
    key: e6qifkcl5445su046f67
    version: e6qm081iujmlv1lu9q3f
  image:
    repository: cr.yandex/crpi7be6fcnum9d5jo38/lms-backend
    tag: 0.0.51
    pullPolicy: IfNotPresent

frontend:
  deploy: true
  port: 3000
  replicas: 4
  image:
    repository: cr.yandex/crpi7be6fcnum9d5jo38/lms-frontend
    tag: 0.0.37
    pullPolicy: IfNotPresent

landing:
  deploy: true
  port: 3000
  replicas: 4
  image:
    repository: cr.yandex/crpi7be6fcnum9d5jo38/lms-landing
    tag: 0.0.18
    pullPolicy: IfNotPresent

idm:
  image:
    repository: cr.yandex/crpi7be6fcnum9d5jo38/idm
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000
  secret:
    key: e6qr44u3hrnb48b2updq
    version: e6qc10h57an7o2oqvtbj
