{{- if .Values.frontend.deploy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: lms-frontend
  template:
    metadata:
      labels:
        app: lms-frontend
    spec:
      imagePullSecrets:
        - name: yandex-cr-auth
      containers:
        - name: lms-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"
---
{{- end }}