{{- if .Values.frontend.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  name: lms-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: lms-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
---
{{- end }}