name: Deploy backend

on:
  push:
    branches: ["mosh"]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    env:
      CARGO_TERM_COLOR: always
      RUST_VERSION: stable
      IMAGE_NAME: cr.yandex/crpi7be6fcnum9d5jo38/lms-mosh-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image version
        run: echo "IMAGE_VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}-cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}-cache,mode=max
